name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  e2e-testes:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Install Node 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run E2E tests
      run: npx playwright test --reporter=list,json

    - name: Install Allure
      run: npm install -g allure-commandline --save-dev

    - name: Generate Allure Report
      run: allure generate ./playwright-report --clean -o ./allure-report

    - name: Publish Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: ./allure-report/
        retention-days: 30

