name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  e2e-testes:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Install Node 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps


    - name: Run Playwright tests
      run: npx playwright test --reporter=line,allure-playwright

    - name: Get Allure history
      if: always()
      run: |
        git fetch origin allure:refs/remotes/origin/allure || echo "No allure branch"
        git checkout allure || git checkout --orphan allure
        mkdir -p allure-history || echo "Allure history directory already exists"
        cp -r allure-history allure-results || echo "No previous allure results to copy"

    - name: Generate Allure Report
      if: always()
      run: |
        npx allure generate allure-results --clean -o allure-history

    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: allure
        publish_dir: allure-history
